kind: Deployment
apiVersion: apps/v1
metadata:
  name: stqwebapp
  namespace: default
  labels:
    k8s-app: stqwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stqwebapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: stqwebapp
    spec:
      containers:
        - name: stqwebapp
          image: 'gcr.io/xxcloud/stqwebapp-dev:86d2a31'
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TZ
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gcr-json-key
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: stqwebapp
  name: stqwebapp
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: stqwebapp        