kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: stqwebapp
  name: stqwebapp
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s-app: stqwebapp
  template:
    metadata:
      labels:
        k8s-app: stqwebapp
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: stqwebapp
          image: gcr.io/xxcloud/stqwebapp:56ffecc
          resources:    
            requests:
              cpu: 0.1            
              memory: 312Mi   
            limits:
              cpu: 0.6            
              memory: 612Mi               
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: redis  
            - name: TRADE_ENV
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TRADE_ENV              
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TZ  
            - name: COUCHBASE_URL
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: url      
            - name: COUCHBASE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: bucket
            - name: COUCHBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: username
            - name: COUCHBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: password    
            - name: NEXT_PUBLIC_PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: PAYPAL_ID     
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: PAYPAL_SECRET                                                                                                                                                                                                                                 

          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: stqwebapp
  name: stqwebapp
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    k8s-app: stqwebapp